version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    volumes:
      - ../test/test Sicurezza:/zap/wrk
    command: >
      zap.sh -cmd -autorun /zap/wrk/zap.yaml
